#!/usr/bin/env python3
"""
Generate THIRD_PARTY_LICENSES from installed package metadata.
Run after updating Python dependencies to keep the file current.

Usage:
    python scripts/gen_licenses.py           # generate THIRD_PARTY_LICENSES
    python scripts/gen_licenses.py --check   # exit(1) if file is out of date
"""
import argparse
import difflib
import importlib.metadata
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REQUIREMENTS = ROOT / "requirements.txt"
OUTPUT = ROOT / "THIRD_PARTY_LICENSES"
LICENSES_DIR = ROOT / "scripts" / "licenses"

# License texts for entries with no locally-inspectable artifact to read from
# (no dist-info like a pip package, no file bundled in an image like the
# manylinux system libraries) live as plain files under scripts/licenses/,
# not inline here, so this file stays logic-only.
OAUTH2_PROXY_ENTRY = {
    "name": "oauth2-proxy",
    "license_id": "MIT",
    "homepage": "https://github.com/oauth2-proxy/oauth2-proxy",
    "note": "Not bundled. Downloaded from GitHub Releases at runtime.",
    "license_text": (LICENSES_DIR / "oauth2-proxy-MIT.txt").read_text(encoding="utf-8").strip("\n"),
}

MANYLINUX_LICENSES_FILE = ROOT / "scripts" / "manylinux_licenses.json"

# Everything here except {version} and the license text itself is editorial and
# hand-maintained. The version + license text come from manylinux_licenses.json,
# which scripts/refresh_manylinux_licenses.py regenerates from the actual RPM
# packages inside the pinned build image (scripts/manylinux_images.json)
# whenever that image is bumped.
# Keys here are stable identifiers, not tied to any version or exact RPM
# package name, so this dict never needs editing just because
# manylinux_images.json's python_version or image digest is bumped -- only
# the values in manylinux_licenses.json (regenerated by
# scripts/refresh_manylinux_licenses.py) change.
SYSTEM_LIBRARY_METADATA = {
    "python": {
        "display_name": "CPython {version} runtime (libpython)",
        "license_id": "PSF-2.0",
        "homepage": "https://www.python.org/",
        "note": "Bundled in the Linux build only.",
    },
    "openssl": {
        "display_name": "OpenSSL {version}",
        "license_id": "OpenSSL AND SSLeay",
        "homepage": "https://www.openssl.org/",
        "note": "Bundled in the Linux build only.",
    },
    "zlib": {
        "display_name": "zlib {version}",
        "license_id": "Zlib",
        "homepage": "https://zlib.net/",
        "note": "Bundled in the Linux build only.",
    },
    "xz": {
        "display_name": "XZ Utils / liblzma {version}",
        "license_id": "Public Domain",
        "homepage": "https://tukaani.org/xz/",
        "note": (
            "Bundled in the Linux build only, and only liblzma itself (public domain) -- "
            "the GPL-licensed command-line tools and scripts in the XZ Utils package are "
            "not bundled. See the file below for the package's full per-file license "
            "breakdown."
        ),
    },
    "libffi": {
        "display_name": "libffi {version}",
        "license_id": "MIT",
        "homepage": "https://sourceware.org/libffi/",
        "note": "Bundled in the Linux build only.",
    },
    "bzip2": {
        "display_name": "bzip2 {version}",
        # Unlike the other entries here, bzip2's SPDX license id is itself
        # versioned (its license text has changed wording between releases,
        # e.g. bzip2-1.0.5 vs bzip2-1.0.6) -- so this must track {version}
        # rather than being a fixed string, or it'll go stale the moment the
        # bundled bzip2 version changes (e.g. when manylinux_images.json is
        # bumped to a newer base image).
        "license_id": "bzip2-{version}",
        "homepage": "https://sourceware.org/bzip2/",
        "note": "Bundled in the Linux build only.",
    },
    "mpdecimal": {
        "display_name": "mpdecimal {version} (libmpdec)",
        "license_id": "BSD-2-Clause",
        "homepage": "https://www.bytereef.org/mpdecimal/",
        "note": "Bundled in the Linux build only.",
    },
}


def _system_library_entries() -> list[dict]:
    data = json.loads(MANYLINUX_LICENSES_FILE.read_text(encoding="utf-8"))
    entries = []
    for pkg, meta in SYSTEM_LIBRARY_METADATA.items():
        pkg_data = data[pkg]
        entries.append({
            "name": meta["display_name"].format(version=pkg_data["version"]),
            "license_id": meta["license_id"].format(version=pkg_data["version"]),
            "homepage": meta["homepage"],
            "note": meta["note"],
            "license_text": pkg_data["license_text"],
        })
    return entries

OPENSSL_APACHE_LICENSE_TEXT = (LICENSES_DIR / "openssl-apache-2.0.txt").read_text(encoding="utf-8").strip("\n")


def _cryptography_openssl_entry() -> dict | None:
    """Detect the OpenSSL version statically linked into the installed `cryptography`
    package, by reading the SBOM it ships in its own dist-info. Returns None if
    `cryptography` isn't installed, or its SBOM doesn't declare a vendored OpenSSL
    (e.g. a future release that drops OpenSSL entirely)."""
    try:
        files = importlib.metadata.files("cryptography")
    except importlib.metadata.PackageNotFoundError:
        return None
    if not files:
        return None
    sbom_file = next((f for f in files if Path(str(f)).name == "sbom.json"), None)
    if sbom_file is None:
        return None
    try:
        data = json.loads(sbom_file.read_text(encoding="utf-8"))
    except Exception:
        return None
    openssl = next(
        (c for c in data.get("components", []) if (c.get("name") or "").lower() == "openssl"),
        None,
    )
    if openssl is None:
        return None
    version = openssl.get("version", "unknown")
    cryptography_version = importlib.metadata.version("cryptography")
    return {
        "name": f"OpenSSL {version} (statically linked into the cryptography package)",
        "license_id": "Apache-2.0",
        "homepage": "https://www.openssl.org/",
        "note": (
            f"Statically linked inside the cryptography {cryptography_version} package's "
            "compiled extension, on all platforms. This is a separate, independently "
            "versioned copy of OpenSSL from the one listed above for the Linux build -- "
            "detected here from cryptography's own bundled SBOM (sboms/sbom.json) at "
            "THIRD_PARTY_LICENSES generation time, so it tracks whatever OpenSSL version "
            "the installed cryptography release vendors."
        ),
        "license_text": OPENSSL_APACHE_LICENSE_TEXT,
    }


HEADER = """\
Third-Party Licenses
====================

This file lists the open-source components used by easyauth-emulator.
Each component retains its original license.

The easyauth-emulator project itself is licensed under the Apache License 2.0
(see LICENSE).

"""

SEP = "=" * 72


def _read_requirements() -> list[str]:
    """Read package names from requirements.txt (strips version specifiers)."""
    packages = []
    for line in REQUIREMENTS.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        # Strip version specifier (==, >=, <=, ~=, !=, >, <)
        for op in ("==", ">=", "<=", "~=", "!=", ">", "<"):
            if op in line:
                line = line[: line.index(op)].strip()
                break
        packages.append(line)
    return packages


def _find_license_text(pkg: str) -> str:
    files = importlib.metadata.files(pkg)
    if not files:
        return ""
    candidates = [
        f for f in files
        if "dist-info" in str(f)
        and any(
            seg in Path(str(f)).name.upper()
            for seg in ("LICENSE", "LICENCE", "COPYING", "COPYRIGHT")
        )
    ]
    for candidate in candidates:
        try:
            text = candidate.read_text(encoding="utf-8")
            if text.strip():
                return text.strip()
        except Exception:
            continue
    return ""


def _license_id(meta: importlib.metadata.PackageMetadata) -> str:
    value = meta.get("License-Expression") or meta.get("License") or ""
    if value:
        return value
    classifiers = meta.get_all("Classifier") or []
    ids = [
        c.split(" :: ")[-1]
        for c in classifiers
        if c.startswith("License ::")
    ]
    return ", ".join(ids)


def _python_package_section(pkg: str) -> str:
    meta = importlib.metadata.metadata(pkg)
    name = meta["Name"]
    version = meta["Version"]
    homepage = meta.get("Home-page") or ""
    license_id = _license_id(meta)
    license_text = _find_license_text(pkg)

    lines = [SEP, f"{name} {version}"]
    if license_id:
        lines.append(f"License: {license_id}")
    if homepage:
        lines.append(f"Homepage: {homepage}")
    lines += [SEP, "", license_text if license_text else "(License text not available in package metadata)"]
    return "\n".join(lines)


def _static_section(entry: dict) -> str:
    lines = [
        SEP,
        entry["name"],
        f"License: {entry['license_id']}",
        f"Homepage: {entry['homepage']}",
        f"Note: {entry['note']}",
        SEP,
        "",
        entry["license_text"],
    ]
    return "\n".join(lines)


def _generate() -> str:
    packages = _read_requirements()
    sections = [_python_package_section(pkg) for pkg in packages]
    sections += [_static_section(entry) for entry in _system_library_entries()]
    cryptography_openssl = _cryptography_openssl_entry()
    if cryptography_openssl is not None:
        sections.append(_static_section(cryptography_openssl))
    sections.append(_static_section(OAUTH2_PROXY_ENTRY))
    return HEADER + "\n\n\n".join(sections) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="Exit with error if THIRD_PARTY_LICENSES is out of date")
    args = parser.parse_args()

    content = _generate()

    if args.check:
        if not OUTPUT.exists():
            print(f"[gen_licenses] ERROR: {OUTPUT.name} does not exist. Run without --check to generate it.", file=sys.stderr)
            sys.exit(1)
        current = OUTPUT.read_text(encoding="utf-8")
        if current != content:
            diff = difflib.unified_diff(
                current.splitlines(keepends=True),
                content.splitlines(keepends=True),
                fromfile=f"{OUTPUT.name} (current)",
                tofile=f"{OUTPUT.name} (expected)",
            )
            print(f"[gen_licenses] ERROR: {OUTPUT.name} is out of date. Run `python scripts/gen_licenses.py` and commit the result.", file=sys.stderr)
            print(f"[gen_licenses] Diff:", file=sys.stderr)
            sys.stderr.writelines(diff)
            sys.exit(1)
        print(f"[gen_licenses] {OUTPUT.name} is up to date.")
    else:
        OUTPUT.write_text(content, encoding="utf-8", newline="\n")
        print(f"[gen_licenses] Written: {OUTPUT}")


if __name__ == "__main__":
    main()
