# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import echo_pb2 as echo__pb2

GRPC_GENERATED_VERSION = '1.82.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in echo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EchoStub:
    """Minimal unary service used to visually confirm whether gRPC calls survive
    being proxied through the EasyAuth Emulator gateway (see ToDo.md).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/echo.Echo/SayHello',
                request_serializer=echo__pb2.HelloRequest.SerializeToString,
                response_deserializer=echo__pb2.HelloReply.FromString,
                _registered_method=True)
        self.EchoStream = channel.stream_unary(
                '/echo.Echo/EchoStream',
                request_serializer=echo__pb2.HelloRequest.SerializeToString,
                response_deserializer=echo__pb2.HelloReply.FromString,
                _registered_method=True)
        self.EchoBidi = channel.stream_stream(
                '/echo.Echo/EchoBidi',
                request_serializer=echo__pb2.HelloRequest.SerializeToString,
                response_deserializer=echo__pb2.HelloReply.FromString,
                _registered_method=True)


class EchoServicer:
    """Minimal unary service used to visually confirm whether gRPC calls survive
    being proxied through the EasyAuth Emulator gateway (see ToDo.md).
    """

    def SayHello(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EchoStream(self, request_iterator, context):
        """Client-streaming: the client sends any number of messages, then a
        single reply is returned once it closes its send side.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EchoBidi(self, request_iterator, context):
        """Bidirectional streaming: one reply per request, interleaved as they
        arrive rather than only after the client closes its send side — proves
        the gateway relays a genuinely open, ongoing stream in both directions.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EchoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=echo__pb2.HelloRequest.FromString,
                    response_serializer=echo__pb2.HelloReply.SerializeToString,
            ),
            'EchoStream': grpc.stream_unary_rpc_method_handler(
                    servicer.EchoStream,
                    request_deserializer=echo__pb2.HelloRequest.FromString,
                    response_serializer=echo__pb2.HelloReply.SerializeToString,
            ),
            'EchoBidi': grpc.stream_stream_rpc_method_handler(
                    servicer.EchoBidi,
                    request_deserializer=echo__pb2.HelloRequest.FromString,
                    response_serializer=echo__pb2.HelloReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'echo.Echo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('echo.Echo', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Echo:
    """Minimal unary service used to visually confirm whether gRPC calls survive
    being proxied through the EasyAuth Emulator gateway (see ToDo.md).
    """

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/echo.Echo/SayHello',
            echo__pb2.HelloRequest.SerializeToString,
            echo__pb2.HelloReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EchoStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/echo.Echo/EchoStream',
            echo__pb2.HelloRequest.SerializeToString,
            echo__pb2.HelloReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EchoBidi(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/echo.Echo/EchoBidi',
            echo__pb2.HelloRequest.SerializeToString,
            echo__pb2.HelloReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
